### ISSUE TITLE
Add License items for bundled dependencies

### ISSUE THREAD

**Issue by maoo** [symphonyoss/bot-twilio#1]
The following files are considered bundled dependencies under BSD clause, as such, they should be mentioned in the `LICENSE` file (there may be others that haven't been detected yet):

- [application/apps/ondobot/assets/js/3rdParty/jquery-sortable.js](https://github.com/symphonyoss/bot-twilio/blob/master/application/apps/ondobot/assets/js/3rdParty/jquery-sortable.js)
- [application/apps/ondobot/assets/js/3rdParty/ace/ace.js](https://github.com/symphonyoss/bot-twilio/blob/master/application/apps/ondobot/assets/js/3rdParty/ace/ace.js)

Example:
```
This product bundles jquery-sortable.js v0.9.13, which is available under a "3-clause BSD" license. For details, see application/apps/ondobot/assets/js/3rdParty/jquery-sortable.js.
```

Apologies for not spotting this earlier.

**Comment by openfly** [comment]
added fun bit... that's the symfuny bot.. not the twilio bot.

**Comment by maoo** [comment]
I couldn't find any dependency in the Python code, so I closed this issue.
